

/*----------------------------------------------------------
MASV: 1712601
HO TEN: Trinh Van Minh
LAB: 04
NGAY: 12/06/2021
----------------------------------------------------------*/
--CAC CAU LENH TAO TABLE 

use QLSV
go


create table SINHVIEN
(
	MASV		NVARCHAR(20),
	HOTEN		NVARCHAR(100)		NOT NULL,
	NGAYSINH	DATETIME,
	DIACHI		NVARCHAR(200),
	MALOP		VARCHAR(20),
	TENDN		NVARCHAR(100)		NOT NULL,
	MATKHAU		VARBINARY(MAX)			NOT NULL,
	
	PRIMARY KEY(MASV)
)

create table NHANVIEN
(
	MANV	VARCHAR(20),
	HOTEN	NVARCHAR(100)	NOT NULL,
	EMAIL	VARCHAR(20),
	LUONG	VARBINARY(MAX),
	TENDN	NVARCHAR(100)	NOT NULL,
	MATKHAU	VARBINARY(MAX)		NOT NULL,

	PRIMARY KEY(MANV)
)
create table LOP
(
	MALOP	VARCHAR(20),
	TENLOP	NVARCHAR(100)	NOT NULL,
	MANV	VARCHAR(20),

	PRIMARY KEY(MALOP)
)
