/*---------------------------------------------------------- 
MASV: 1712601 - 1712633
HO TEN CAC THANH VIEN NHOM: Trịnh Văn Minh, Nguyễn Long Nhật
LAB: 03 - NHOM 
NGAY: 10/05/2021
----------------------------------------------------------*/ 

-- CAU LENH TAO STORED PROCEDURE


use QLSVNhom
go

ALTER DATABASE QLSVNhom
SET COMPATIBILITY_LEVEL = 120

--DROP procedure SP_INS_PUBLIC_NHANVIEN
create procedure SP_INS_PUBLIC_NHANVIEN
@MANV VARCHAR(20),@HOTEN NVARCHAR(100),@EMAIL VARCHAR(20),@LUONGCB int,@TENDN NVARCHAR(100),@MK VARCHAR(20)
as 
    DECLARE @ASK NVARCHAR(MAX) = 
    'create asymmetric key NV01
     with algorithm = RSA_512
     encryption by password = '''+@MK+''''
    EXEC(@ASK)
    insert into NHANVIEN values (@MANV,@HOTEN,@EMAIL,ENCRYPTBYASYMKEY(ASYMKEY_ID('NV01'),CONVERT(VARBINARY,@LUONGCB)),@TENDN,HASHBYTES('SHA1',@MK),@MANV)
	--DROP asymmetric key NV01
GO

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
SELECT * FROM NHANVIEN


--drop PROCEDURE SP_SEL_PUBLIC_NHANVIEN 
CREATE PROCEDURE SP_SEL_PUBLIC_NHANVIEN 
@TENDN NVARCHAR(100), @MK VARCHAR(20)
AS
	SELECT MANV, HOTEN, EMAIL,TENDN, LUONGCB = CONVERT(INT, DECRYPTBYASYMKEY(ASYMKEY_ID('NV01'),LUONG, CONVERT(NVARCHAR, @MK)))
	FROM NHANVIEN
	WHERE MANV = @TENDN AND HASHBYTES('SHA1',@MK) = MATKHAU

GO

EXEC SP_SEL_PUBLIC_NHANVIEN 'NV01', 'abcd12'
SELECT *  FROM NHANVIEN


DROP asymmetric key NV01